### PR TITLE
fix: unexpected empty lines when copying-pasting

### LINKED ISSUE #563: Unexpected empty lines when copying-pasting
### Describe the bug

Hello!

When I copy text in memo using selection, in pasting blank lines appear between. Expected that this to work like the built-in copy function works now, without gaps.

https://user-images.githubusercontent.com/118022040/203881939-a18b5c73-d028-4599-9570-5509b1799c2a.mov

### Steps to reproduce

1. Select text in a memo
2. Copy it with `ctrl+c` or using context menu
3. Paste in some input field/text editor

### Screenshots or additional context

I didn't dive deep into what goes to clipboard, but in some text editors it can be pasted with no empty lines, some not. In my glance, this is because of memo markup. Every line goes into the own paragraph.
```html
<p>First line</p>
<p>Second line</p>
```
Which, without clipboard control, leads to this issue.

### PR DESCRIPTION
**Pull request by CorrectRoadH**
close #563 #1524
In #1524, the author has not responded for a long time. So I submit the PR.👀

### CODE REVIEW

File: web/src/components/MemoList.tsx [hunk 1]
```diff
@@ -148,6 +149,21 @@ const MemoList = () => {
     }
   };
 
+  useEffect(() => {
+    addEventListener("copy", handleCopy);
```
Comment (boojack) [inline web/src/components/MemoList.tsx:153]: window.addXXX

**Review by boojack — CHANGES_REQUESTED** [review]

**Comment by CorrectRoadH** [comment]
@boojack PTAL

**Review by boojack — APPROVED** [review]
LGTM
