### PR TITLE
fix: private memos being public

### LINKED ISSUE #2462: Disable public memos - not working
### Describe the bug

The flag "Disable public memos" does not block public notes from being created or viewed publicly.

### Steps to reproduce

1. enable "Disable public memos"
2. create a public note
3. browse to the public note from unauth session

### Screenshots or additional context

_No response_

### PR DESCRIPTION
**Pull request by itschip**
- fix(web/memo): filter out public option
- feat(api/memo): sanity check for disabled public memos

Resolves #2462

Screenshot 2023-11-03 at 13 56 16
Screenshot 2023-11-03 at 13 58 00

### CODE REVIEW

**Comment by itschip** [comment]
We could also disable the select option. What do you like the best @boojack

File: api/v1/memo.go [hunk 1]
```diff
@@ -313,6 +313,11 @@ func (s *APIV1Service) CreateMemo(c echo.Context) error {
 				createMemoRequest.Visibility = Private
 			}
 		}
+
+		// sanity check for visibility
+		if createMemoRequest.Visibility == Public && disablePublicMemos {
```
Comment (boojack) [inline api/v1/memo.go:318]: Right now we allow admin to create public contents. And I think it's works good for me. 

So this check might be unnecessary.

https://github.com/usememos/memos/pull/2480/files#diff-e1e4065afaaae81d389a92c11ef9ac0fdbec4681bc20647843ce88dcf0193420L311

Comment (itschip) [reply api/v1/memo.go:318]: Ah, missed that. Sounds good!

**Comment by itschip** [comment]
@boojack We have access to the user role on the frontend, correct? If so, I'll just disable the public option if you're not an admin. Does that sound cool?

File: web/src/components/MemoEditor/index.tsx [hunk 2]
```diff
@@ -465,12 +472,15 @@ const MemoEditor = (props: Props) => {
...
             {VISIBILITY_SELECTOR_ITEMS.map((item) => (
-              <Option key={item} value={item} className="whitespace-nowrap">
+              <Option key={item} value={item} className="whitespace-nowrap" disabled={disableOption(item)}>
                 {t(`memo.visibility.${item.toLowerCase() as Lowercase<typeof item>}`)}
               </Option>
             ))}
           </Select>
         </div>
+        <div className="flex-grow">
+          {systemStatus.disablePublicMemos && <Typography color="warning">{t("memo.visibility.disabled")}</Typography>}
```
Comment (boojack) [inline web/src/components/MemoEditor/index.tsx:482]: This warning text might be too long in mobile view. Let's remove it.

**Comment by boojack** [comment]
> @boojack We have access to the user role on the frontend, correct? (HOST?) If so, I'll just disable the public option if you're not an admin. Does that sound cool?

SGTM

File: web/src/pages/MemoDetail.tsx [hunk 3]
```diff
@@ -156,12 +165,15 @@ const MemoDetail = () => {
...
                     >
                       {VISIBILITY_SELECTOR_ITEMS.map((item) => (
-                        <Option key={item} value={item} className="whitespace-nowrap">
+                        <Option key={item} value={item} className="whitespace-nowrap" disabled={disableOption(item)}>
                           {t(`memo.visibility.${item.toLowerCase() as Lowercase<typeof item>}`)}
                         </Option>
                       ))}
                     </Select>
-                  </>
+                    <div className="flex-grow">
```
Comment (boojack) [inline web/src/pages/MemoDetail.tsx:173]: And this warning text should be removing too.

**Review by boojack — APPROVED** [review]
LGTM, thanks for your contribution!

File: web/src/pages/MemoDetail.tsx (hunk 3 above)
Comment (itschip) [reply web/src/pages/MemoDetail.tsx]: Done @boojack
