### PR TITLE
fix: database is locked

### LINKED ISSUE #1985: Cannot log in - db locking issue - failed to find users
### Describe the bug

Sometimes when I apply hashtag or upload a post, I will get kicked out with message cannot find user=1, and when I try to log in again, I get "failed to find users"

Upon further research, it seems that my meemo is locking. I've checked ps and no other process is being used, and there is no memory or ram issues... also checked sqlite3 integrity check is fine. If I restart docker, the lock is released and can post/login again.

```

2023-07-14T18:21:41Z method=GET uri=/api/tag? status=500 error=code=500, message=Server error to find user ID: 1, internal=SQL logic error: cannot start a transaction within a transaction (1)

2023-07-14T18:21:41Z method=GET uri=/api/memo/stats?creatorId=1 status=500 error=code=500, message=Server error to find user ID: 1, internal=SQL logic error: cannot start a transaction within a transaction (1)

2023-07-14T18:21:41Z method=GET uri=/api/user/1 status=500 error=code=500, message=Server error to find user ID: 1, internal=database is locked (5) (SQLITE_BUSY)

2023-07-14T18:21:41Z method=GET uri=/api/shortcut? status=500 error=code=500, message=Server error to find user ID: 1, internal=database is locked (5) (SQLITE_BUSY)

2023-07-14T18:21:41Z method=GET uri=/api/user/1 status=500 error=code=500, message=Server error to find user ID: 1, internal=database is locked (5) (SQLITE_BUSY)

```
terminated received.

### Steps to reproduce

1. post something / hashtag
2. error occurs
3. No longer sees login but "Sign Up" button and when I put username password admin/password, it will say "failed to find users" as shown in screenshot below

### Screenshots or additional context

image

### PR DESCRIPTION
**Pull request by lincolnthalles**
The option "_journal_mode=WAL" is currently *not* being applied when provided in the DSN.

This issue affects only new memos installations, not older ones where the database journal was properly set to WAL mode by the previous sqlite library go-sqlite3.

[modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite) DSN parsing is different from [go-sqlite3](https://github.com/mattn/go-sqlite3). It requires the `_pragma=` prefix and even some options order matter.
https://gitlab.com/cznic/sqlite/-/issues/115

By the way, as stated at sqlite documentation, it's a good practice to keep "cache=private" and "foreign_keys=0" explicit, even though it's the current default behavior, as sqlite defaults may change at some point.

Closes #1985

### CODE REVIEW

File: store/db/db.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func (db *DB) Open(ctx context.Context) (err error) {
 	}
 
 	// Connect to the database without foreign_key.
-	sqliteDB, err := sql.Open("sqlite", db.profile.DSN+"?cache=private&_foreign_keys=0&_busy_timeout=10000&_journal_mode=WAL")
+	sqliteDB, err := sql.Open("sqlite", db.profile.DSN+"?cache=private&_pragma=foreign_keys=0&_pragma=busy_timeout=10000&_pragma=journal_mode=WAL")
```
Comment (boojack) [inline store/db/db.go:46]: Could you please add some comments with the related reference docs?

**Review by boojack — APPROVED** [review]
LGTM
