### PR TITLE
Fixes #4604: Support Child Tags in NSFW Blur Feature

### LINKED ISSUE #4604: Support Child Tags in NSFW Blur Feature
### Describe the bug

Currently, only direct #nsfw tags trigger memo blurring, while child tags like #nsfw/waifu remain unblurred. 

I believe any tag containing #nsfw as root parent (through slash hierarchy) should trigger blur.

### Steps to reproduce

1 Add #nsfw to nsfw tag lists
2 Create a memo with #nsfw tag - blurs correctly
3 Create a memo with #nsfw/waifu tag - remains unblurred

### The version of Memos you're using

0.24.2

### Screenshots or additional context

_No response_

### PR DESCRIPTION
**Pull request by jmlt2002**
My fix supports what is described in the issue, if tags like "#something/nsfw" or "#blabla-nsfw-blabla" are also supposed to be supported, a quick change can be made from this `tag.startsWith("nsfw")` to this `tag.includes("nsfw")`.

### CODE REVIEW

**Comment by Cadavanaugh** [comment]
Hey jmlt2002. I think it's suitable for you to assign the related issue to this PR so it's more documented https://github.com/usememos/memos/issues/4604

**Comment by johnnyjoygh** [comment]
Maybe we should check whether it belongs to one of the NSFW tags as they may be customizable, and not always limited to `nsfw`.

**Review by johnnyjoygh — APPROVED** [review]
LGTM

File: web/src/components/MemoView.tsx [hunk 1]
```diff
@@ -59,8 +59,13 @@ const MemoView: React.FC<Props> = (props: Props) => {
...
   const nsfw =
-    workspaceMemoRelatedSetting.enableBlurNsfwContent &&
-    memo.tags?.some((tag) => workspaceMemoRelatedSetting.nsfwTags.includes(tag.toLowerCase()));
+  workspaceMemoRelatedSetting.enableBlurNsfwContent &&
+  memo.tags?.some((tag) =>
+    workspaceMemoRelatedSetting.nsfwTags.some((nsfwTag) =>
+      tag === nsfwTag ||
+      tag.startsWith(`${nsfwTag}/`)
+    )
+  );
```
Comment (johnnyjoygh) [inline web/src/components/MemoView.tsx:68]:
```suggestion
    workspaceMemoRelatedSetting.enableBlurNsfwContent &&
    memo.tags?.some((tag) => workspaceMemoRelatedSetting.nsfwTags.some((nsfwTag) => tag === nsfwTag || tag.startsWith(`${nsfwTag}/`)));
```
