### PR TITLE
fix: access token refresh on web app

### LINKED ISSUE #5658: Notes disappearing when returning to homepage
### Pre-submission Checklist

- [x] I have searched the existing issues and this bug has not been reported yet
- [x] I have tested this issue on the [demo site](https://demo.usememos.com) or the latest version

### Where did you encounter this bug?

Latest stable version (self-hosted)

### Memos Version

v0.26.2

### Bug Description

When leaving the page (browser tab) and returning after a while, the notes disappear. Checking the console shows that a request is sent to `/memos.api.v1.UserService/ListUserNotifications` which is failing with status 401.
Notes return when refreshing the page.

### Steps to Reproduce

1. Open memos and login
2. Go to the homepage where your notes are listed
3. Leave the page by switching tabs and wait for a while, I would say more than 15 minutes at least
4. Return to the page

### Expected Behavior

I expect the notes not to disappear and the user to stay authorized.

### Screenshots & Additional Context

- Google Chrome and Brave (happens on both)
- Docker Image v0.26.2
- Ubuntu
- Proxied by Cloudlare Tunnel (cloudflared)

### PR DESCRIPTION
**Pull request by peteretelej**
A bug exists within the token refresh flow that invalidates active browser sessions. Retrieving the active access token returns `null` if it's expired. Seem like a small oversight when token storage was migrated to the jwt tokens.

This means expired tokens don't refresh, and if leave the browser tab idle for 15min, the tab drops auth context and shows logged out view (you're still logged in though - reload fixes it). A few issues are open for this.

Resolves #5658, #5607, #5589, #5565
(last 3 are closed but underlying issue persisted)

May also fix some of the other issues where drafts keep getting lost (but I'm not sure, may be that the reauth is what makes the draft get lost)

### CODE REVIEW

File: web/src/hooks/useTokenRefreshOnFocus.ts [hunk 1]
```diff
@@ -20,9 +20,8 @@ export function useTokenRefreshOnFocus(refreshFn: () => Promise<void>, enabled:
         return;
       }
 
-      // Only refresh if we have a token
-      const token = getAccessToken();
```
Comment (peteretelej) [inline web/src/hooks/useTokenRefreshOnFocus.ts:24]: this was the bug: `getAccessToken()` returns null if the token we have is expired, meaning we don't get a chance to refresh it

**Review by boojack — APPROVED** [review]
LGTM, good catch

**Comment by theacodes** [comment]
Started running into this today and noticed it was fixed but not yet released, would it be possible to get a new release out soon? Thank you

**Comment by boojack** [comment]
@theacodes This has already been included in our latest RC release: https://github.com/usememos/memos/releases/tag/v0.27.0-rc.2

**Comment by theacodes** [comment]
Ah I see, my docker image is pulling 0.26.2 since that's the latest
non-prerelease. I'll try out the pre releases, thank you!

**Comment by iioel** [comment]
Good catch ! This actually fixed the issue I created: https://github.com/usememos/memos/issues/5643
